package svg

type PresentationAttributes struct {
	AlignmentBaseline          string `xml:"alignment-baseline,attr,omitempty"`
	BaselineShift              string `xml:"baseline-shift,attr,omitempty"`
	Clip                       string `xml:"clip,attr,omitempty"`
	ClipPath                   string `xml:"clip-path,attr,omitempty"`
	ClipRule                   string `xml:"clip-rule,attr,omitempty"`
	Color                      string `xml:"color,attr,omitempty"`
	ColorInterpolation         string `xml:"color-interpolation,attr,omitempty"`
	ColorInterpolationFilters  string `xml:"color-interpolation-filters,attr,omitempty"`
	ColorProfile               string `xml:"color-profile,attr,omitempty"`
	ColorRendering             string `xml:"color-rendering,attr,omitempty"`
	Cursor                     string `xml:"cursor,attr,omitempty"`
	D                          string `xml:"d,attr,omitempty"`
	Direction                  string `xml:"direction,attr,omitempty"`
	Display                    string `xml:"display,attr,omitempty"`
	DominantBaseline           string `xml:"dominant-baseline,attr,omitempty"`
	EnableBackground           string `xml:"enable-background,attr,omitempty"`
	Fill                       string `xml:"fill,attr,omitempty"`
	FillOpacity                string `xml:"fill-opacity,attr,omitempty"`
	FillRule                   string `xml:"fill-rule,attr,omitempty"`
	Filter                     string `xml:"filter,attr,omitempty"`
	FloodColor                 string `xml:"flood-color,attr,omitempty"`
	FloodOpacity               string `xml:"flood-opacity,attr,omitempty"`
	FontFamily                 string `xml:"font-family,attr,omitempty"`
	FontSize                   string `xml:"font-size,attr,omitempty"`
	FontSizeAdjust             string `xml:"font-size-adjust,attr,omitempty"`
	FontStretch                string `xml:"font-stretch,attr,omitempty"`
	FontStyle                  string `xml:"font-style,attr,omitempty"`
	FontVariant                string `xml:"font-variant,attr,omitempty"`
	FontWeight                 string `xml:"font-weight,attr,omitempty"`
	GlyphOrientationHorizontal string `xml:"glyph-orientation-horizontal,attr,omitempty"`
	GlyphOrientationVertical   string `xml:"glyph-orientation-vertical,attr,omitempty"`
	ImageRendering             string `xml:"image-rendering,attr,omitempty"`
	Kerning                    string `xml:"kerning,attr,omitempty"`
	LetterSpacing              string `xml:"letter-spacing,attr,omitempty"`
	LightingColor              string `xml:"lighting-color,attr,omitempty"`
	MarkerEnd                  string `xml:"marker-end,attr,omitempty"`
	MarkerMid                  string `xml:"marker-mid,attr,omitempty"`
	MarkerStart                string `xml:"marker-start,attr,omitempty"`
	Mask                       string `xml:"mask,attr,omitempty"`
	Opacity                    string `xml:"opacity,attr,omitempty"`
	Overflow                   string `xml:"overflow,attr,omitempty"`
	PointerEvents              string `xml:"pointer-events,attr,omitempty"`
	ShapeRendering             string `xml:"shape-rendering,attr,omitempty"`
	SolidColor                 string `xml:"solid-color,attr,omitempty"`
	SolidOpacity               string `xml:"solid-opacity,attr,omitempty"`
	StopColor                  string `xml:"stop-color,attr,omitempty"`
	StopOpacity                string `xml:"stop-opacity,attr,omitempty"`
	Stroke                     string `xml:"stroke,attr,omitempty"`
	StrokeDasharray            string `xml:"stroke-dasharray,attr,omitempty"`
	StrokeDashoffset           string `xml:"stroke-dashoffset,attr,omitempty"`
	StrokeLinecap              string `xml:"stroke-linecap,attr,omitempty"`
	StrokeLinejoin             string `xml:"stroke-linejoin,attr,omitempty"`
	StrokeMiterlimit           string `xml:"stroke-miterlimit,attr,omitempty"`
	StrokeOpacity              string `xml:"stroke-opacity,attr,omitempty"`
	StrokeWidth                string `xml:"stroke-width,attr,omitempty"`
	TextAnchor                 string `xml:"text-anchor,attr,omitempty"`
	TextDecoration             string `xml:"text-decoration,attr,omitempty"`
	TextRendering              string `xml:"text-rendering,attr,omitempty"`
	Transform                  string `xml:"transform,attr,omitempty"`
	UnicodeBidi                string `xml:"unicode-bidi,attr,omitempty"`
	VectorEffect               string `xml:"vector-effect,attr,omitempty"`
	Visibility                 string `xml:"visibility,attr,omitempty"`
	WordSpacing                string `xml:"word-spacing,attr,omitempty"`
	WritingMode                string `xml:"writing-mode,attr,omitempty"`
}
